schema_version = "1.0.0"

id = "export_curve_as_svg"
version = "2.0.0"
name = "Export Curve as SVG"
tagline = "Export curves and other geometry as SVG paths"
maintainer = "Gilberto Rodrigues"
type = "add-on"
website = "https://github.com/GilbertoRodrigues/export_curve_as_svg"
tags = ["Import-Export"]
blender_version_min = "5.0.0"
license = [
  "SPDX:GPL-3.0-or-later",
]

[permissions]
files = "Export SVG files to a user-selected location"

[build]
paths_exclude_pattern = [
  "__pycache__/",
  "/.git/",
  "/*.zip",
  "/icons/generate.py",
]